spring:
  # datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  redis:
    host: localhost
    port: 6379
    #password:
    chanel-name: verificationQueue

# eureka server url
eureka:
  client:
    service-url:
      default-zone: http://${eureka-host:localhost}:${eureka-port:8761}/eureka

token:
  expirationTime:
    # 7 days
    access: 604800000
    # 100 days
    refresh: 8640000000



