# serivce name
spring:
  application:
    name: account-service
  mvc:
    logResolvedException: false


server:
  port: 8210

db:
  schema: account

security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    service-url:
      default-zone: http://${eureka-host}:${eureka-port}/eureka

