image: ubuntu

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'


docker-deploy:
  stage: deploy
  script:
    - ssh root@207.154.239.122
    - $SSH_PRIVATE_KEY
    - pwd
    - ls /usr/
  only:
    - karma/dev
