stages:
  - prebuild
  - build
  - stop-container
  - prepackage
  - package
  - deploy
  
variables:
  PROJECT_HOME: "/usr/gliesereum"
  
git-pull:
  stage: prebuild
  script:
    - echo 'Git pull'
    - cd $PROJECT_HOME
    - git pull
  only:
    - karma/dev

gradle-build:
  stage: build
  script:
    - echo 'Gradle build'
    - cd $PROJECT_HOME
    - sudo gradle clean build -b=account/build.gradle
    - sudo gradle clean build -b=discovery/build.gradle
    - sudo gradle clean build -b=proxy/build.gradle
    - sudo gradle clean build -b=mail/build.gradle
    - sudo gradle clean build -b=permission/build.gradle
    - sudo gradle clean build -b=karma/build.gradle
    - sudo gradle clean build -b=media/build.gradle
  only:
    - karma/dev

docker-stop-container:
  stage: stop-container
  script:
    - echo 'Docker stop containers'
    - cd $PROJECT_HOME
    - docker stack rm gls
    - sleep 30
    - docker rm $(docker ps -a -q) --force
  only:
    - karma/dev
  allow_failure: true

docker-clean-image:
  stage: prepackage
  script:
    - echo 'Docker clean images'
    - cd $PROJECT_HOME
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-discovery')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-account')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-proxy')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-mail')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-permission')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-karma')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-media')
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'gls-curator')
  only:
    - karma/dev
  allow_failure: true
    
docker-image-package:
  stage: package
  script:
    - echo 'Docker build images'
    - cd $PROJECT_HOME
    - sudo docker build -t gls-discovery:0.0.1 -f docker/discovery/Dockerfile  ./discovery/build/libs/
    - sudo docker build -t gls-account:0.0.1 -f docker/account/Dockerfile  ./account/build/libs/
    - sudo docker build -t gls-proxy:0.0.1  -f docker/proxy/Dockerfile  ./proxy/build/libs/
    - sudo docker build -t gls-mail:0.0.1 -f docker/mail/Dockerfile  ./mail/build/libs/
    - sudo docker build -t gls-permission:0.0.1 -f docker/permission/Dockerfile  ./permission/build/libs/
    - sudo docker build -t gls-karma:0.0.1 -f docker/karma/Dockerfile  ./karma/build/libs/
    - sudo docker build -t gls-media:0.0.1 -f docker/media/Dockerfile  ./media/build/libs/
    - sudo docker build -t gls-curator:0.0.1 -f docker/curator/Dockerfile  ./log/elk/
  only:
    - karma/dev

docker-deploy:
  stage: deploy
  script:
    - echo 'Docker deploy'
    - cd $PROJECT_HOME
    - docker stack deploy -c docker/docker-compose-dev-log.yml gls
    - docker ps
  only:
    - karma/dev
