spring:
  datasource:
    url: jdbc:postgresql://207.154.239.122:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  redis:
    host: 207.154.239.122
    port: 6379
    password: Af2f4dsASF
    chanel-logstash: logstash

  flyway:
    enabled: true
    locations: classpath:db/migration/all,classpath:db/migration/data
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  data:
    jest:
      uri: http://207.154.239.122:9200