spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/postgres
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration/all,classpath:db/migration/data
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  rabbitmq:
    host: ${rabbit.host}
    port: ${rabbit.port}
    password: ${rabbit.password}
    username: ${rabbit.user}
    queue-logstash: logstash

  data:
    jest:
      uri: http://${es.host}:${es.port}
      max-connection-idle-time: 5000
      read-timeout: 5000