spring:
  application:
    name: notification-service
  mvc:
    logResolvedException: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true

module-url: /notification/v1

server:
  port: 8270

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

db:
  schema: notification

security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

exchange:
  endpoint:
    permission:
      endpointUpdatePack: http://permission-service/endpoint/pack
    account:
      userIsExist: http://account-service/user/exist
      findByIds: http://account-service/user/by-ids
    karma:
      businessForCurrentUser: http://karma-service/business/by-current-user
      existChatSupport: http://karma-service/chat-support/exist-chat-support

firebase:
  properties:
    credentialPath: classpath:google-services.json
    appName: karma-c9d57

notification:
  record:
    queueName: notification-record
  business:
    queueName: notification-business
  chat-message:
    queueName: notification-chat-message