# serivce name
spring:
  application:
    name: proxy-service


server:
  port: ${port:8200}

zuul:
  routes:
    account-service:
      path: /account/v1/**
      service-id: account-service
    mail-service:
      path: /mail/v1/**
      service-id: mail-service
  ignored-services: '*'
  prefix: /api
  host:
    connectTimeoutMillis: 100000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
