# serivce name
spring:
  application:
    name: proxy-service


server:
  port: ${port:8200}

zuul:
  routes:
    account-service:
      path: /account/v1/**
      service-id: account-service
    mail-service:
      path: /mail/v1/**
      service-id: mail-service
  ignored-services: '*'
  prefix: /api
  host:
    connectTimeoutMillis: 10000
  add-host-header: true
  sensitive-headers:

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

security:
  properties:
    checkAccessUrl: http://account-service/auth/check
    bearerHeader: Authorization
    bearerPrefix: Bearer
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE