# serivce name
spring:
  application:
    name: proxy-service

server:
  port: 8200

zuul:
  routes:
    account-service:
      path: /account/v1/**
      service-id: account-service
    mail-service:
      path: /mail/v1/**
      service-id: mail-service
    karma-service:
      path: /karma/v1/**
      service-id: karma-service
  ignored-services: '*'
  prefix: /api
  host:
    connectTimeoutMillis: 30000
    socket-timeout-millis: 30000
  add-host-header: true
  sensitive-headers:

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 80000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 280000


security:
  properties:
    checkAccessUrl: http://account-service/auth/check
    bearerHeader: Authorization
    bearerPrefix: Bearer
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true