spring:
  application:
    name: lending-gallery-service
  mvc:
    logResolvedException: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true

module-url: /lending-gallery/v1

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 8260

db:
  schema: lending_gallery

security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

exchange:
  endpoint:
    permission:
      endpointUpdatePack: http://permission-service/endpoint/pack
      getGroupUserByGroupPurpose: http://permission-service/group-user/by-group-purpose
    account:
      userIsExist: http://account-service/user/exist
      findByIds: http://account-service/user/by-ids
      findDetailedByIds: http://account-service/user/detailed/by-ids