admin:
  email: gliesereum@gmail.com

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: gliesereum@gmail.com
    password: Gliesereum0013
    from: GLIESEREUM<gliesereum@gmail.com>
    subject: Gliesereum verification mail
    chanel-verification: verificationQueue
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
            trust: "*"
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

phone:
  url: https://acemountmedia.com/api/
  auth-type: token
  alpha-name: SECURITY
  login: businesseuropolicy
  token: shiM8uESwOEAWEurmDWGNmY6LPSy_x1m


