spring:
  application:
    name: mail-service

db:
  schema: mail

server:
  port: 8220

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

module-url: /mail/v1


security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

exchange:
  endpoint:
    account:
      findUserPhonesByUserIds: http://account-service/phone/by-user-ids

telegram:
  bot:
    feed-back:
      token: 914987096:AAFJWyVEq7Qu9DQru0dhve8N64GpIcHUtkM
      user-name: feedBack_bot
      message:
        start: "couplerFeedBack connected to this chat: "
        end: "couplerFeedBack disconnected to this chat: "
        help: "/start connected bot to chat\n/end disconnected bot to chat"