version: '3.1'

services:
  postgres:
    volumes:
      - ../pgdata/:/var/lib/postgresql/data
    image: postgres:10.5-alpine
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - 5432:5432