version: '3.1'

services:
#  postgres:
#    image: postgres:10.5-alpine
#    command: postgres -c 'max_connections=500' -c 'shared_buffers=256MB'
#    volumes:
#      - ../volumes/pgdata/:/var/lib/postgresql/data
#    deploy:
#      restart_policy:
#        condition: on-failure
#    environment:
#      POSTGRES_PASSWORD: Af2f4dsASF
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#    ports:
#      - 5432:5432

  redis:
    image: redis:4.0.11-alpine
    command: >
      --loglevel ${REDIS_LOGLEVEL:-notice}
      --save 900 1
      --save 300 10
      --save 60 10000
      --requirepass Af2f4dsASF
    volumes:
      - ../volumes/redisdata/:/data
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: Af2f4dsASF
    deploy:
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      ES_JAVA_OPTS: "-Xms300M -Xmx1536M"
    ports:
    - 9200:9200
    - 9300:9300
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 20
    volumes:
    - ../volumes/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 20

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    environment:
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: rabbit
      RABBIT_PASSWORD: Af2f4dsASF
      ES_HOST: elasticsearch
      ES_PORT: 9200
      LS_JAVA_OPTS: "-Xms100M -Xmx1G"
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 20
    volumes:
    - ../log/elk/logstash/logstash.dev.conf:/usr/share/logstash/pipeline/logstash.conf

  curator:
    image: gls-curator:0.0.1
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
      CRON: '15 0 * * *'
      #CRON: '*/5 * * * *'
      CONFIG_FILE: /curator/config/curator.yml
      COMMAND: /curator/config/actions.yml
      UNIT_COUNT: 3
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
    - ../log/elk/curator:/.curator
    - ../log/elk/curator/logs:/curator/logs/

  discovery:
    image: gls-discovery:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8761
      spring.profiles.active: docker
      eureka.instance.hostname: discovery

  account:
    image: gls-account:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8210
      spring.profiles.active: docker
      db.host: db-postgresql-fra1-37757-do-user-3517380-0.db.ondigitalocean.com
      db.database: defaultdb
      db.port: 25060
      db.username: doadmin
      db.password: sfnb4k42qcunuqgr
      redis.host: redis
      redis.port: 6379
      redis.password: Af2f4dsASF
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      eureka.host: discovery
      eureka.port: 8761

  mail:
    image: gls-mail:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8220
      spring.profiles.active: docker
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      eureka.host: discovery
      eureka.port: 8761

  proxy:
    image: gls-proxy:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8200
      spring.profiles.active: docker
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      eureka.host: discovery
      eureka.port: 8761

  permission:
    image: gls-permission:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8230
      spring.profiles.active: docker
      db.host: db-postgresql-fra1-37757-do-user-3517380-0.db.ondigitalocean.com
      db.database: defaultdb
      db.port: 25060
      db.username: doadmin
      db.password: sfnb4k42qcunuqgr
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      eureka.host: discovery
      eureka.port: 8761

  karma:
    image: gls-karma:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8230
      spring.profiles.active: docker
      db.host: db-postgresql-fra1-37757-do-user-3517380-0.db.ondigitalocean.com
      db.database: defaultdb
      db.port: 25060
      db.username: doadmin
      db.password: sfnb4k42qcunuqgr
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      es.host: elasticsearch
      es.port: 9200
      eureka.host: discovery
      eureka.port: 8761

  file:
    image: gls-file:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      server.port: 8250
      spring.profiles.active: docker
      db.host: db-postgresql-fra1-37757-do-user-3517380-0.db.ondigitalocean.com
      db.database: defaultdb
      db.port: 25060
      db.username: doadmin
      db.password: sfnb4k42qcunuqgr
      rabbit.host: rabbit
      rabbit.port: 5672
      rabbit.user: rabbit
      rabbit.password: Af2f4dsASF
      cdn.accessKey: XJSIQ6UA5HZEHMH3DDUP
      cdn.secretKey: C5PSCSJgAG4VaCYUSJaK9SA/pDHX/kE7BLatMHEz90I
      cdn.host: sgp1.digitaloceanspaces.com
      cdn.region: sgp1
      cdn.bucket: glcdn
      cdn.folder: karma
      eureka.host: discovery
      eureka.port: 8761

  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - ../nginx-dev:/etc/nginx
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 5601:5601
      - 8200:8200
