dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation "org.apache.commons:commons-collections4:${commonsCollectionsVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLangVersion}"
    implementation "commons-io:commons-io:${commonsIOVersion}"
    implementation "org.modelmapper:modelmapper:${modelMapperVersion}"
    implementation "io.jsonwebtoken:jjwt:${jjwtVersion}"
    implementation "io.springfox:springfox-swagger2:${swaggerVersion}"
    implementation "com.amazonaws:aws-java-sdk-s3:${awsVersion}"

    implementation(project(':share')) {
        transitive = false
    }

    runtimeOnly 'org.postgresql:postgresql'
    testImplementation "ch.qos.logback:logback-classic:${logbackVersion}"
}
