spring:
  application:
    name: payment-service

db:
  schema: payment

server:
  port: 8280

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

module-url: /payment/v1


security:
  properties:
    jwtHeader: Service-Authorization
    jwtPrefix: JWT
    jwtSecret: CnfxFqbCKHLqzT9LGruE

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
    registry-fetch-interval-seconds: 20
    availability-zones:
      default: defaultZone
    region: default
    enabled: true
  instance:
    prefer-ip-address: true

exchange:
  endpoint:
    account:
      findUserPhonesByUserIds: http://account-service/phone/by-user-ids

liq-pay:
  crypto:
    password: eD6fB08A179e
    salt: f57P7bCf25dc2e
  public-key: sandbox_i68717225710
  private-key: sandbox_MbnwJt32pvmXEFielzRaM2gYB4tauUmpYM4a3qFs

liq-pay-exchange:
  order-update-info:
    exchange-name: liq-pay-exchange-order-update-info

way-for-pay:
  url:
    api: https://api.wayforpay.com/api
    verify: https://secure.wayforpay.com/verify
    verify-card-response: https://82ddbd7b.ngrok.io/way-for-pay/verify-card-response
  merchant:
   # key: 6c7018b67af807221b14e3e472e1cf57731f9dbd
   # account: coupler_app
   # domain: https://coupler.app/
    key: flk3409refn54t54t*FNJRET
    account: test_merch_n1
    domain: merchant.com.ua

