dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-zuul'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation "org.apache.commons:commons-collections4:${commonsCollectionsVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLangVersion}"
    implementation "org.modelmapper:modelmapper:${modelMapperVersion}"
    implementation "io.jsonwebtoken:jjwt:${jjwtVersion}"
    implementation "io.springfox:springfox-swagger2:${swaggerVersion}"
    implementation "io.springfox:springfox-swagger-ui:${swaggerVersion}"

    // JDK 11 removed java.xml.bind, which the Eureka client's XML codecs need.
    implementation "javax.xml.bind:jaxb-api:${jaxbApiVersion}"
    implementation "com.sun.xml.bind:jaxb-core:${jaxbCoreVersion}"
    implementation "com.sun.xml.bind:jaxb-impl:${jaxbImplVersion}"
    implementation "javax.activation:activation:${javaxActivationVersion}"

    implementation "org.cache2k:cache2k-api:${cache2kVersion}"
    implementation "org.cache2k:cache2k-jcache:${cache2kVersion}"
    runtimeOnly "org.cache2k:cache2k-core:${cache2kVersion}"

    implementation(project(':share')) {
        transitive = false
    }

    testImplementation 'org.springframework.security:spring-security-test'
}
