dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation "org.apache.commons:commons-collections4:${commonsCollectionsVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLangVersion}"
    implementation "commons-io:commons-io:${commonsIOVersion}"
    implementation "org.modelmapper:modelmapper:${modelMapperVersion}"
    implementation "io.jsonwebtoken:jjwt:${jjwtVersion}"
    implementation "io.projectreactor.netty:reactor-netty:${reactorNettyVersion}"

    implementation(project(':share')) {
        transitive = false
    }
}
