spring:
  # datasource configuration
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/postgres
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  redis:
    host: ${redis.host}
    port: ${redis.port}
    #password: ${redis.password}
    chanel-logstash: logstash

logging:
  file: logs/permission.log


